spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/test
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      mode: never
  graphql:
    graphiql:
      enabled: true
    path: /graphql
    websocket:
      path: /graphql
